// Generated by uniffi-bindgen-react-native
#include "react-native-matrix-sdk.h"
#include "generated/matrix_sdk_ffi.hpp"
#include "generated/matrix_sdk_ui.hpp"

namespace matrixsdk {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeMatrixSdkFfi::registerModule(runtime, callInvoker);
		NativeMatrixSdkUi::registerModule(runtime, callInvoker);
		return false;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}