// Generated by uniffi-bindgen-react-native
#include "react-native-matrix-sdk.h"
#include "generated/matrix_sdk.hpp"
#include "generated/matrix_sdk_base.hpp"
#include "generated/matrix_sdk_common.hpp"
#include "generated/matrix_sdk_crypto.hpp"
#include "generated/matrix_sdk_ffi.hpp"
#include "generated/matrix_sdk_ui.hpp"

namespace reactnativematrixsdk {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeMatrixSdk::registerModule(runtime, callInvoker);
		NativeMatrixSdkBase::registerModule(runtime, callInvoker);
		NativeMatrixSdkCommon::registerModule(runtime, callInvoker);
		NativeMatrixSdkCrypto::registerModule(runtime, callInvoker);
		NativeMatrixSdkFfi::registerModule(runtime, callInvoker);
		NativeMatrixSdkUi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}