#ifndef UNOMED_REACTNATIVEMATRIXSDK_H
#define UNOMED_REACTNATIVEMATRIXSDK_H
// Generated by uniffi-bindgen-react-native
#include <cstdint>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvoker.h>

namespace unomed_reactnativematrixsdk {
  using namespace facebook;

  uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker);
  uint8_t cleanupRustCrate(jsi::Runtime &runtime);
}

#endif /* UNOMED_REACTNATIVEMATRIXSDK_H */