// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-matrix-sdk.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNMatrixSdkSpec.h"

@interface MatrixSdk : NSObject <NativeMatrixSdkSpec>
#else
#import <React/RCTBridgeModule.h>

@interface MatrixSdk : NSObject <RCTBridgeModule>
#endif

@end