// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "unomed-react-native-matrix-sdk.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "NativeReactNativeMatrixSdkSpec.h"

@interface ReactNativeMatrixSdk : NSObject <NativeReactNativeMatrixSdkSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ReactNativeMatrixSdk : NSObject <RCTBridgeModule>
#endif

@end