// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "unomed-react-native-matrix-sdk.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "NativeReactNativeMatrixSdkSpec.h"

@interface UnomedReactNativeMatrixSdk : NSObject <NativeUnomedReactNativeMatrixSdkSpec>
#else
#import <React/RCTBridgeModule.h>

@interface UnomedReactNativeMatrixSdk : NSObject <RCTBridgeModule>
#endif

@end