// Generated by uniffi-bindgen-react-native
import installer from './NativeMatrixSdk';

// Register the rust crate with Hermes
installer.installRustCrate();

// Export the generated bindings to the app.
export * from './generated/matrix_sdk_ffi';
export * from './generated/matrix_sdk_ui';

// Initialize the generated bindings: mostly checksums, but also callbacks.
import matrix_sdk_ffi_ from './generated/matrix_sdk_ffi';
import matrix_sdk_ui_ from './generated/matrix_sdk_ui';

matrix_sdk_ffi_.initialize();
matrix_sdk_ui_.initialize();
