name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
      - name: Setup JS
        uses: ./.github/actions/setup-js

      - name: Setup Rust (Android)
        if: ${{ inputs.platform == 'android' }}
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Setup Rust (iOS)
        if: ${{ inputs.platform == 'ios' }}
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios,aarch64-apple-ios-sim,x86_64-apple-ios

      - name: Install cargo-ndk
        if: ${{ inputs.platform == 'android' }}
        shell: bash
        run: cargo install cargo-ndk

      - name: Write .xcode.env.local
        if: ${{ inputs.platform == 'ios' }}
        shell: bash
        run: |
          # Work around for https://github.com/facebook/react-native/issues/35657
          echo "export NODE_BINARY=$(which node)" >> example/ios/.xcode.env.local
          cat example/ios/.xcode.env.local

      - name: Generate (Android)
        if: ${{ inputs.platform == 'android' }}
        shell: bash
        run: yarn generate:android

      - name: Generate (iOS)
        if: ${{ inputs.platform == 'ios' }}
        shell: bash
        run: yarn generate:ios

      - name: Free space
        shell: bash
        run: rm -rf rust_modules

      # TODO: Figure out why this fails
      # - name: Check if repository is dirty
      #   shell: bash
      #   run: |
      #     if [[ -n "$(git status --porcelain)" ]]; then
      #       >&2 echo "Found unexpected changes in repository after generating"
      #       git status --short
      #       exit 1
      #     fi

