name: Android (Generate)
on:
  # TODO: remove
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate
        uses: ./.github/actions/generate
        with:
          platform: android
          # TODO: uncomment
          # release: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-libs
          path: android/**/*.a
          if-no-files-found: error
