name: iOS (Generate)
on:
  # TODO: remove
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate
        uses: ./.github/actions/generate
        with:
          platform: ios
          # TODO: uncomment
          # release: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xcframework
          path: build/*.xcframework
          if-no-files-found: error
