name: Release
on:
  # TODO: remove
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate
        uses: ./.github/actions/generate
        with:
          platform: android
          # TODO: uncomment
          # release: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libs
          path: android/**/*.a
          if-no-files-found: error

  generate-ios:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate
        uses: ./.github/actions/generate
        with:
          platform: ios
          # TODO: uncomment
          # release: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xcframework
          path: build/*.xcframework
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: [generate-android, generate-ios]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: libs
          path: android

      - uses: actions/download-artifact@v4
        with:
          name: xcframework
          path: build

      - name: Install gh
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Upload attachments
        run: |
          # TODO: Consume from input
          tag=0.4.0

          # TODO: compress & upload
          # gh release upload "$tag" "$FILE"

      - name: TODO
        run: tree

        