name: Release
on:
  # TODO: remove
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate
        uses: ./.github/actions/generate
        with:
          platform: android

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libs
          path: android/**.a
          if-no-files-found: error

  generate-ios:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate
        uses: ./.github/actions/generate
        with:
          platform: ios

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xcframework
          path: build/*.xcframework
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: [generate-android, generate-ios]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: libs
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: xcframework
          path: .

      - name: TODO
        run: tree